version: "3.7"

services:
  dataproc_1_4_14:
    image: de-spark-dataproc-1.4.14-debian9:${DOCKER_GIT_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPARK_VERSION: 2.3.2
        HADOOP_VERSION: 2.7.5
        HIVE_VERSION: 1.2.2
        SCALA_VERSION: 2.11.12
        SBT_VERSION: 1.2.8
        SPARK_MAJOR_MINOR_VERSION: 2.3
